### ISSUE TITLE
mini not set correctly in Pedal.calibrate()

### ISSUE THREAD

**Issue by The-Chris-Davies** [The-Chris-Davies/SAEelectricpedal#2]
when run, mini is always set to 0

**Comment by LastChanceBilly** [comment]
Well, since mini was set to 0, it was not going to read anything lower than that.
I added:
```
bool flag =1;
	while(!Serial.available()){
		//Store the value of 'rot' into mini just on the first cycle
		mini = flag == 1 ? analogRead(rot) >> 4: mini;
		flag =0;
                ....
```
So it'll first store 'rot' into mini, and then compare mini to the values of currVal every cycle, so mini will only be as low as the lowest value returned by analogRead(rot)>>4.
What do you think?

**Comment by The-Chris-Davies** [comment]
mini should have been set to -1 during Pedal::Pedal(), making it the largest possible value, but this works.
